baseURL = "https://jsteinsson.github.io/"
relativeURLs = true
title = "Jon Steinsson"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Marek Professor of Public Policy and Economics, University of California, Berkeley"
    logo = "images/jon-steinsson.jpg"
    faviconVersion = "4"
    logoVersion = "2"
    
